### ISSUE TITLE
can not access the AdminPortal

### ISSUE THREAD

**Issue by keefer223** [OnFireGroup/Tutorial-yiimp-2022-working#1]
followed the instructions as outlined, however I cannot access the AdminPortal.

Computer: duel core/dual processor with 8g of memory
Computer IP: 192.168.1.108 
Domain: nextgenmining.net

System appears to be up:

Welcome to Ubuntu 18.04.6 LTS (YiiMP Version).

System information as of: Sat Apr 30 08:51:59 EDT 2022

  System load:  1.01               Processes:             206
  Usage of /:   4.6% of 234.67GB   Users logged in:       1
  Memory usage: 24%                IP address for enp0s3: 192.168.1.108
  Swap usage:   0%

YiiMP Information:
==================================================
 Main:   running       Daemon Directory: /home/yiimp-data/wallets
 Blocks: running       YiiMP Directory: /home/yiimp-data/yiimp/site
 Loop2:  running       Hint: To view a screen type, screen -r main|loop2|blocks|debug                
 Debug:  running       Hint: To detach from a screen type, ctrl+a+d                

To start|stop|restart a screen use the following command...
screens start|stop|restart main|loop2|blocks|debug

To reload this MOTD just type motd...

0 updates can be applied immediately.

.yiimp.conf:
STORAGE_USER=yiimp-data
STORAGE_ROOT=/home/yiimp-data
PRIMARY_HOSTNAME=nextgenmining.net

UsingDomain=yes
UsingSubDomain=no
DomainName=nextgenmining.net
StratumURL=nextgenmining.net
InstallSSL=yes
SupportEmail=root@localhost

AdminPanel=AdminPortal
PublicIP=192.168.1.16
CoinPort=yes
AutoExchange=no

**Comment by OnFireGroup** [comment]
Hello, go to /home/yiimp-data/yiimp/.yiimp.conf instead of your local ip, put your external ip (PublicIP=192.168.1.16 to PublicIP=YOUR EXTERNAL IP)
  https://whatismyipaddress.com/
