### ISSUE TITLE
script stop Nginx error

### ISSUE THREAD

**Issue by sp1k36667** [OnFireGroup/Tutorial-yiimp-2022-working#2]
Upgrading NGINX...
rm: cannot remove '/etc/nginx/sites-enabled/default*': No such file or directory
An error occurred in line 46 of file nginx_upgrade.sh:
sudo rm -r /etc/nginx/sites-enabled/default*

**Comment by OnFireGroup** [comment]
Hello, I Will help you, check If there is a file in the Path indicated /etc/nginx/sites-enabled/default, If there até no files, create It.
Check If the script is running as SU
